### PR TITLE
💄UI: Update default neutral colors and accent colors.

### PR DESCRIPTION
**Pull request by CosAnca**
- neutral colors values changed to slightly different shades of gray
- neutral colors palette extended with the introduction of steps `30`, 
`40` and `60` for a more streamlined scale
- accent colors values changed to slightly different shades of blue
- accent colors palette extended with the introduction of `ultralight` 
and `ultradark` variants

### CODE REVIEW

**Comment by dennisreimann** [comment]
I know this might just be a start, but I'm not convinced with the choice of colors – or at least the way the UI looks with them applied. Especially the sidebar does not look good and the structure get's lost as the general light background does not work with the dark bg of the sublevels.

colors

**Comment by CosAnca** [comment]
Oh, totally. My initial thinking was I would just update the neutral and accent color palettes here and then update the navigation style in a later PR related to #63 but now I realise it makes more sense to update the colors throughout the entire application in a single PR so we don't get this kind of issues. I'll update this PR with more color changes.

**Comment by dennisreimann** [comment]
Yeah, go ahead. You don‘t need to be too fine grained – something like 4-6 PRs for everything you proposed might suffice. Just wanted to ensure that it‘s not one big bang of changes (that‘s also hard to review). As long as it‘s a coherent chunk and not 5k lines changed you are good to go 😉

**Comment by CosAnca** [comment]
I made some more changes to the styles of the "application shell" and updated this PR with a couple commits.
Basically now the topbar and the navigation sidebar should look very much like in the proposal (except it doesn't include the new font change which is addressed in PR #76 )

**Comment by dennisreimann** [comment]
Awesome, good work! 👍

**Pull request merged**
