### PR TITLE
💄UI: Update contentheader and iconography

### PR DESCRIPTION
**Pull request by CosAnca**
- Cleanup icons folder
- Update currently in use icons with slightly thicker and rounder 
versions for improved readability
- Update style of contentheader tablist options to a buttons group
- Update contentheader actions icons
- Update application layout by moving the contentheader variants links 
to their own fixed in page navigation on the right hand side
- Replace "Preview" label with preview icon
- Replace "Code" label with code icon
- Update style of contentheader label and tag
- Fix an issue with topbar search rendering too small if no theme 
switcher present
- Fix an issue with contentsection list items rendering the underline 
across the comma separator and the ending dot.

### CODE REVIEW

**Comment by CosAnca** [comment]
This PR addresses issue #60 and #64 mainly but also includes a couple of fixes for recent changes.
Most of the file changes are coming from the icons folder cleanup where only 16 _updated_ icon files were left in there from the previous 125 total.

**Comment by dennisreimann** [comment]
Awesome, looking very good 👍

A few things I noticed …

## Component

* The h1 is really huge, I'd make it a tad smaller.
* The "Composed of" / "Used by" links have browser deefault styles
links

## Preview 

* In viewport mode, the preview area spans too wide.
preview

## Templates

* For templates (MainTemplate.vue) some things are a bit off, mostly regarding the tabs. It's unfortunate that this is a separate thing from MainComponent.vue, but I haven't gotten around to clean it up, yet. There's duplication between those page components, from what I imaginge it should be just a few styles missing that are already part of MainComponent.vue

tab1

tab2

**Comment by CosAnca** [comment]
Good catch for the MainTemplate. Thank you. I didn't realise it was using a separate file.
I have just pushed some changes to address all the points in your comment above.

- Reduced the font size of `h1`
- Updated the style for links in "Composed of" and "Used within" lists
- Fixed the preview area spanning width issue when on Viewport mode
- Updated the components of MainTemplate to match the layout and style of the ones in MainComponent

**Comment by dennisreimann** [comment]
Brilliant 👍

**Pull request merged**
